"""add processed_at to documents table

Revision ID: 2ce8ee5c628c
Revises: d5a7b8c9f3e2
Create Date: 2025-06-27 14:43:30.446778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ce8ee5c628c'
down_revision: Union[str, None] = 'd5a7b8c9f3e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_chat_messages_chat_id'), table_name='chat_messages')
    op.drop_index(op.f('idx_chats_user_id_document_id'), table_name='chats')
    op.drop_index(op.f('idx_document_chunks_document_id'), table_name='document_chunks')
    op.drop_index(op.f('idx_document_tags_both'), table_name='document_tags')
    op.add_column('documents', sa.Column('processed_at', sa.DateTime(), nullable=True))
    op.drop_index(op.f('idx_documents_deleted_at_null'), table_name='documents', postgresql_where='(archived_at IS NULL)')
    op.drop_index(op.f('idx_documents_folder_id_user_id'), table_name='documents')
    op.drop_index(op.f('idx_documents_user_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_deleted_at'), table_name='documents')
    op.drop_index(op.f('ix_documents_status'), table_name='documents')
    op.create_index(op.f('ix_documents_archived_at'), 'documents', ['archived_at'], unique=False)
    op.drop_index(op.f('idx_folder_tags_both'), table_name='folder_tags')
    op.drop_index(op.f('idx_folders_deleted_at_null'), table_name='folders', postgresql_where='(archived_at IS NULL)')
    op.drop_index(op.f('ix_folders_deleted_at'), table_name='folders')
    op.create_index(op.f('ix_folders_archived_at'), 'folders', ['archived_at'], unique=False)
    op.drop_constraint(op.f('folders_parent_id_fkey'), 'folders', type_='foreignkey')
    op.create_foreign_key(None, 'folders', 'folders', ['parent_id'], ['id'])
    op.drop_index(op.f('idx_summaries_user_id'), table_name='summaries')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_summaries_user_id'), 'summaries', ['user_id'], unique=False)
    op.drop_constraint(None, 'folders', type_='foreignkey')
    op.create_foreign_key(op.f('folders_parent_id_fkey'), 'folders', 'folders', ['parent_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_folders_archived_at'), table_name='folders')
    op.create_index(op.f('ix_folders_deleted_at'), 'folders', ['archived_at'], unique=False)
    op.create_index(op.f('idx_folders_deleted_at_null'), 'folders', ['archived_at'], unique=False, postgresql_where='(archived_at IS NULL)')
    op.create_index(op.f('idx_folder_tags_both'), 'folder_tags', ['folder_id', 'tag_id'], unique=False)
    op.drop_index(op.f('ix_documents_archived_at'), table_name='documents')
    op.create_index(op.f('ix_documents_status'), 'documents', ['status'], unique=False)
    op.create_index(op.f('ix_documents_deleted_at'), 'documents', ['archived_at'], unique=False)
    op.create_index(op.f('idx_documents_user_id'), 'documents', ['user_id'], unique=False)
    op.create_index(op.f('idx_documents_folder_id_user_id'), 'documents', ['folder_id', 'user_id'], unique=False)
    op.create_index(op.f('idx_documents_deleted_at_null'), 'documents', ['archived_at'], unique=False, postgresql_where='(archived_at IS NULL)')
    op.drop_column('documents', 'processed_at')
    op.create_index(op.f('idx_document_tags_both'), 'document_tags', ['document_id', 'tag_id'], unique=False)
    op.create_index(op.f('idx_document_chunks_document_id'), 'document_chunks', ['document_id'], unique=False)
    op.create_index(op.f('idx_chats_user_id_document_id'), 'chats', ['user_id', 'document_id'], unique=False)
    op.create_index(op.f('idx_chat_messages_chat_id'), 'chat_messages', ['chat_id'], unique=False)
    # ### end Alembic commands ###
