"""Add extracted_text and word_count to documents table

Revision ID: 499ee5d80a69
Revises: 23804b4f39d0
Create Date: 2025-06-10 13:12:09.420855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '499ee5d80a69'
down_revision: Union[str, None] = '23804b4f39d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('extracted_text', sa.Text(), nullable=True))
    op.add_column('documents', sa.Column('word_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'word_count')
    op.drop_column('documents', 'extracted_text')
    # ### end Alembic commands ###
