"""add updated_at to documents table

Revision ID: a9132ced46c7
Revises: f44d9c81df20
Create Date: 2025-06-27 14:59:55.226148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9132ced46c7'
down_revision: Union[str, None] = 'f44d9c81df20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # First add the column as nullable
    op.add_column('documents', sa.Column('updated_at', sa.DateTime(), nullable=True))
    
    # Update existing rows to use created_at as the initial updated_at value
    op.execute('UPDATE documents SET updated_at = created_at WHERE updated_at IS NULL')
    
    # Now make the column NOT NULL
    op.alter_column('documents', 'updated_at', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'updated_at')
    # ### end Alembic commands ###
