"""Make storage_path nullable for text summaries

Revision ID: c142041b5ea0
Revises: 648d2c7e14b6
Create Date: 2025-06-06 16:53:53.577520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c142041b5ea0'
down_revision: Union[str, None] = '648d2c7e14b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'storage_path',
                    existing_type=sa.String(length=500),
                    nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'storage_path',
                    existing_type=sa.String(length=500),
                    nullable=False)
    # ### end Alembic commands ###
