"""add error_message to documents table

Revision ID: f44d9c81df20
Revises: 2ce8ee5c628c
Create Date: 2025-06-27 14:45:40.763185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f44d9c81df20'
down_revision: Union[str, None] = '2ce8ee5c628c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('error_message', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'error_message')
    # ### end Alembic commands ###
