"""Add smart folders with tag associations

Revision ID: 375b75e28a08
Revises: a6affcf4a903
Create Date: 2025-06-12 13:40:36.520268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '375b75e28a08'
down_revision: Union[str, None] = 'a6affcf4a903'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('folder_tags',
    sa.Column('folder_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['folder_id'], ['folders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('folder_id', 'tag_id')
    )
    op.add_column('folders', sa.Column('is_smart', sa.Boolean(), nullable=False, server_default='false'))
    op.drop_constraint(op.f('folders_parent_id_fkey'), 'folders', type_='foreignkey')
    op.create_foreign_key(None, 'folders', 'folders', ['parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop the foreign key constraint by finding its actual name
    op.drop_constraint('folders_parent_id_fkey', 'folders', type_='foreignkey')
    op.create_foreign_key(op.f('folders_parent_id_fkey'), 'folders', 'folders', ['parent_id'], ['id'], ondelete='CASCADE')
    op.drop_column('folders', 'is_smart')
    op.drop_table('folder_tags')
    # ### end Alembic commands ###
