"""Add soft delete fields for trash functionality

Revision ID: a6affcf4a903
Revises: d8414762858c
Create Date: 2025-06-12 02:19:43.905649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6affcf4a903'
down_revision: Union[str, None] = 'd8414762858c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_documents_deleted_at'), 'documents', ['deleted_at'], unique=False)
    op.add_column('folders', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_folders_deleted_at'), 'folders', ['deleted_at'], unique=False)
    # Don't need to modify the foreign key constraint
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Don't need to modify the foreign key constraint
    op.drop_index(op.f('ix_folders_deleted_at'), table_name='folders')
    op.drop_column('folders', 'deleted_at')
    op.drop_index(op.f('ix_documents_deleted_at'), table_name='documents')
    op.drop_column('documents', 'deleted_at')
    # ### end Alembic commands ###
